export const dataCourse = [
  { id: 1, 
    intro: false,
    course_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25"], 
    title: "IBM Data Science", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png?auto=format%2Ccompress&dpr=2&w=120&h=120&q=40"],
    org: ["IBM"], 
    rating: "4.6 (88.3k reviews)", 
    enrolled: "1.1m students", 
    meta_data: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    product: "",
    category: "",
    credit: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 2, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/ba/e14875b76f4e799e067d3551076e8c/1200x600_DA.png?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    title: "Google Data Analytics", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-instructor-photos.s3.amazonaws.com/61/36584e2633455296817e987d653e8d/500x500_Google.jpg?auto=format%2Ccompress&dpr=2&w=36&h="],
    org: ["Google"], 
    rating: "4.8 (47.4k reviews)", 
    enrolled: "770k students", 
    meta_data: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: ["New"],
    skills: "Spreadsheet, Data Cleansing, Data Analysis, Data Visualization (DataViz), SQL, Questioning, Decision-Making, Problem Solving, Metadata, Data Collection, Data Ethics, Sample Size Determination",
    product: "plus",
    category: "plus",
    credit: "Earn credit towards your degree",
    url: "https://www.coursera.org/professional-certificates/google-data-analytics"
  },
  { id: 3, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/eb/8e18e0a4f111e59ae9c776a3dd0526/jhu-logo-thumb.png?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    title: "Data Science", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-university-assets.s3.amazonaws.com/74/7ae340ec6911e5b395490a2a565172/JHU-Logo-Square-Mini_180px.png?auto=format%2Ccompress&dpr=2&w=120&h=120&q=40"],
    org: ["Johns Hopkins University"], 
    rating: "4.8 (27.1k reviews)", 
    enrolled: "480k students", 
    meta_data: ["Beginner", "Specialization", "3+ Months"], 
    status: ["New"],
    skills: "Github, Machine Learning, R Programming, Regression Analysis, Data Science, Rstudio, Data Analysis, Debugging, Data Manipulation, Regular Expression (REGEX), Data Cleansing, Cluster Analysis",
    product: "plus",
    category: "plus",
    credit: "",
    url: "https://www.coursera.org/specializations/jhu-data-science"
  },
  { id: 4, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/c8/8d6df01eb311e6b5f5f786b289d8ba/pythondatascience_specialization_final.png?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    title: "Applied Data Science with Python", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-university-assets.s3.amazonaws.com/70/de505d47be7d3a063b51b6f856a6e2/New-Block-M-Stacked-Blue-295C_600x600.png?auto=format%2Ccompress&dpr=2&w=72&h=72&fit=crop"],
    org: ["University of Michigan"], 
    rating: "4.5 (31.5k reviews)", 
    enrolled: "800k students", 
    meta_data: ["Intermediate", "Specialization", "3+ Months"], 
    status: [],
    skills: "Text Mining, Python Programming, Pandas, Matplotlib, Numpy, Data Cleansing, Data Virtualization, Data Visualization (DataViz), Machine Learning (ML) Algorithms, Machine Learning, Scikit-Learn, Natural Language Toolkit (NLTK)",
    product: "plus",
    category: "plus",
    credit: "",
    url: "https://www.coursera.org/specializations/data-science-python"
  },
  { id: 5, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/32/d719a2d0d946d59e1151bc10ec29f5/Specialization-Certificate-Emblem---IDS---600x600.png?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    title: "Introduction to Data Science", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png?auto=format%2Ccompress&dpr=2&w=120&h=120&q=40"],
    org: ["IBM"], 
    rating: "4.6 (65.6k reviews)", 
    enrolled: "690k students", 
    meta_data: ["Beginner", "Specialization", "3+ Months"], 
    status: ["Beta"],
    skills: "Data Science, Relational Database Management System (RDBMS), Cloud Databases, Python Programming, SQL, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Jupyter notebooks, Rstudio",
    product: "credit",
    category: "",
    credit: "Earn credit towards your degree",
    url: "https://www.coursera.org/specializations/introduction-data-science"
  },
  { id: 6, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/bd/0202c87e244d30bdecd889bd2719ae/DataScienceFundamentalsPythonSQL.png?auto=format%2Ccompress&dpr=2&w=150&h=150&q=25&fit=fill&bg=FFF", 
    title: "Data Science Fundamentals with Python and SQL", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png?auto=format%2Ccompress&dpr=2&w=120&h=120&q=40"],
    org: ["IBM"], 
    rating: "4.6 (43.9k reviews)", 
    enrolled: "580k students", 
    meta_data: ["Beginner", "Specialization", "3+ Months"], 
    status: [],
    skills: "Data Science, Github, Python Programming, Jupyter notebooks, Rstudio, Data Analysis, Pandas, Numpy, Ipython, Probability And Statistics, Regression Analysis, Data Visualization (DataViz)",
    product: "credit",
    category: "",
    credit: "Earn credit towards your degree",
    url: "https://www.coursera.org/specializations/data-science-fundamentals-python-sql"
  },
  { id: 7, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/63/baf9bea98641aeb8fd36a7b1291791/DA-PC_Image.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&q=25&fit=fill&bg=FFF", 
    title: "Fintech: Foundations & Applications of Financial Technology Specialization", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png?auto=format%2Ccompress&dpr=2&w=120&h=120&q=40"],
    org: ["IBM"], 
    rating: "4.6 (46.2k reviews)", 
    enrolled: "730k students", 
    meta_data: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Microsoft Excel, Python Programming, Data Analysis, Data Visualization (DataViz), SQL, Data Science, Spreadsheet, Pivot Table, IBM Cognos Analytics, Dashboard, Pandas, Numpy",
    product: "credit",
    category: "",
    credit: "Earn credit towards your degree",
    url: "https://www.coursera.org/professional-certificates/ibm-data-analyst"
  },
  { id: 8, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/ddp/branding/bcs-uol/thumbnail.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&q=25&fit=fill&bg=FFF", 
    title: "Bachelor of Science in Computer Science", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/fb/b28a301e0211e8a40e23e4176c8e4a/UoL-Logo_180x180.png?auto=format%2Ccompress&dpr=2&w=72&h=72&fit=crop"],
    org: ["University of London"], 
    rating: "", 
    enrolled: "", 
    meta_data: ["Degree", "3+ Months"], 
    status: [],
    skills: "",
    product: "degree",
    category: "",
    credit: "",
    url: "https://www.coursera.org/specializations/bi-foundations-sql-etl-data-warehouse?"
  },
  { id: 9, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/5d/2e87b05b9b48c482d132ee5d89cddc/nicholas-cappello-Wb63zqJ5gnE-unsplash.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&q=25&fit=fill&bg=FFF", 
    title: "Regression and Classification", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/ddp/branding/msee-boulder/CUBoulder_360x360.png?auto=format%2Ccompress&dpr=2&w=72&h=72&fit=crop"],
    org: ["University of Colorado Boulder"], 
    rating: "", 
    enrolled: "", 
    meta_data: ["Intermediate", "Course", "1-4 Weeks"], 
    status: [],
    skills: "Statistics, Data Science, R Programming",
    product: "plus",
    category: "plus",
    credit: [],
    url: "https://www.coursera.org/search?query=data%20science&"
  },
  { id: 10, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/58/ab336088f511e8944e7b54193638b4/Specialization_Certificate_Emblem_-_AADS_-__Final.png?auto=format%2Ccompress&dpr=2&w=150&h=150&q=25&fit=fill&bg=FFF", 
    title: "Advanced Data Science with IBM", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png?auto=format%2Ccompress&dpr=2&w=120&h=120&q=40"],
    org: ["IBM"], 
    rating: "4.3 (2.8k reviews)", 
    enrolled: "120k students", 
    meta_data: ["Advanced", "Specialization", "3-4 Months"], 
    status: [],
    skills: "Data Science, Internet Of Things (IOT), Deep Learning, Apache Spark, Statistics, Machine Learning, Long Short-Term Memory (ISTM)",
    product: "",
    category: "",
    credit: "",
    url: "https://www.coursera.org/specializations/advanced-data-science-ibm"
  },  
  { id: 11, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/3a/6189bc40a148aca35fed825ccfb891/Specialization-Logo.png?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    title: "Practical Data Science", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/b4/5cb90bb92f420b99bf323a0356f451/Icon.png?auto=format%2Ccompress&dpr=2&w=120&h=120&q=40"],
    org: ["DeepLearningAI"], 
    rating: "4.5 (269 reviews)", 
    enrolled: "17k students", 
    meta_data: ["Advanced", "Specialization", "1-3 Months"], 
    status: [],
    skills: "Natural Language Processing with BERT, ML Pipelines and ML Operations (MLOps), A/B Testing and Model Deployment, Data Labeling at Scale, Automated Machine Learning (AutoML), Statistical Data Bias Detection, Multi-class Classification with FastText and BlazingText, Data ingestion, Exploratory Data Analysis, ML Pipelines and MLOps, Model Training and Deployment with BERT, Model Debugging and Evaluation",
    product: "credit",
    category: "",
    credit: "Earn credit towards your degree",
    url: "https://www.coursera.org/specializations/practical-data-science"
  }, 
  { id: 12, 
    intro: false,
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/9a/a0d7131af944ebbc335e2f60409e6e/specialization_-CFA-Institute-Data-Science-for-Investment.png?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    title: "Data Science for Investment Professionals", 
    org_img: ["https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/1e/b944bdb16247cb977a54eb8860f5e9/cfa-logo-360-min.png?auto=format%2Ccompress&dpr=2&w=120&h=120&q=40"],
    org: ["CFA Institute"], 
    rating: "4.8 (9 reviews)", 
    enrolled: "1.7k students", 
    meta_data: ["Beginner", "Specialization", "3+ Months"], 
    status: [],
    skills: "Data Science, Ethics, Machine Learning, Python Programming, Communication, General Statistics, Statistical Hypothesis Testing, Logistic Regression Modeling, Linear Regression Modeling, Statistical Concepts, Investment",
    product: "credit",
    category: "",
    credit: "Earn credit towards your degree",
    url: "https://www.coursera.org/specializations/data-science-investment-professionals"
  },
]